### ISSUE TITLE
Add `shape` bool flag to cli

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#118]
If we are using an SQL database then we need the structure of the underlying API requests to build migrations to create tables to import into. It is a [bad practice ](https://stackoverflow.com/questions/46572117/is-it-a-good-idea-to-create-tables-dynamically-to-store-user-content) to dynamically create SQL tables. So the `shape` flag will create an output `.sql` file with the recommended "shape" of the migration based on sampling the API. Nothing will be upstream for these cases, to avoid collision.

```
gidari --config /path/to/config.yml --shape 
```

**Comment by amoghrajesh** [comment]
@prestonvasquez i would like to work on this as part of Hacktoberfest 2022. Could you attach some beginner resources and assign it to me?

**Comment by prestonvasquez** [comment]
@amoghrajesh I'm not entirely sure yet on how this would work. However, it would end up being a "milestone" or "epic" and be broken into many issues. Do you have thoughts on a path forward?
