### ISSUE TITLE
`make containers` cleanup

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#133]

**Comment by snapdgn** [comment]
would love to take this up :)

**Comment by prestonvasquez** [comment]
@snapdgn FYI this issue is not part of Hacktoberfest because it's requirements are not clearly defined. I'm sure these scripts could use some love, though. If you find something that requires complexity and adds value to the repository we can re-purpose this ticket as part Hacktoberfest.

Are you still interested?

**Comment by snapdgn** [comment]
Thank you for the details. would nevertheless like to contribute:). Is it okay if I spend some time poking around other issues? If this one isn't a top priority, I'll return to it later.

**Comment by prestonvasquez** [comment]
Absolutely! Thank you @snapdgn , you're assigned!

**Comment by prestonvasquez** [comment]
Closed by #360
