### ISSUE TITLE
Add Versioning rules to documentaiton

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#141]
This project should use [semantic versioning](https://semver.org/). This ticket includes creating a workflow document for incrementing the version.

**Comment by MrTanoshii** [comment]
I would like to work on this

**Comment by prestonvasquez** [comment]
@MrTanoshii You're assigned!

**Comment by prestonvasquez** [comment]
@MrTanoshii Going to take this one over.

**Comment by MrTanoshii** [comment]
> @MrTanoshii Going to take this one over.

Alright no worries, I've been a bit busy with life, sorry

**Comment by prestonvasquez** [comment]
@MrTanoshii Absolutely, no worries! :)
