### ISSUE TITLE
fill in installation section of readme

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#156]
This only needs to include the `go install ...` information.

**Comment by MrTanoshii** [comment]
I would like to work on this

**Comment by prestonvasquez** [comment]
@MrTanoshii Sounds good, you should know that this doesn't qualify as a Hacktoberfest ticket due to it's simplicity. Are you still interested in working onit?

**Comment by MrTanoshii** [comment]
Yes, I'm thinking of combining a few issues into a PR so it fulfills the complexity criteria

Doing this first will help me get familiar with the project

**Comment by prestonvasquez** [comment]
@MrTanoshii You're assigned!

**Comment by prestonvasquez** [comment]
This was completed as of #216
