### ISSUE TITLE
Add URL host to the transport web worker logs

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#165]
Right now we only log the endpoint once it has been successfully fetched:

```
INFO[0000] {w:4, worker:web, d:77.5965ms, m:web request completed: /fdsnws/event/1/query}
```

We want to also add the host before the request is made. It should look something like this:

```
INFO[0000] {w:4, worker:web,  m:web request host: https://earthquake.usgs.gov }
```

**Comment by PankhudiB** [comment]
Hello @prestonvasquez , I can work on this. 
From what I understood we need to make changes to the tools.LogFormatter and introduce host.

**Comment by prestonvasquez** [comment]
@PankhudiB I was thinking of embedding it the message, but I like your suggestion better!

**Comment by ChandanChainani** [comment]
@prestonvasquez please close the issue since it is done
