### ISSUE TITLE
Add a warning string is no connectionStrings are defined in the config file

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#190]

**Comment by rangzen** [comment]
I will push something regarding this one. Let me know if I misunderstood.

**Comment by prestonvasquez** [comment]
@rangzen Sounds good, I will assign you. FYI though, this issue is not complex enough to be considered for Hacktoberfest. Are you still interested?

**Comment by prestonvasquez** [comment]
@rangzen  Are you still interested in pursuing this issue?

**Comment by rangzen** [comment]
Hello @prestonvasquez, the MR is merged, do you need something else?
