### ISSUE TITLE
Remove the required condition on rateLimit

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#191]
`rateLimit` should not be a required field in the configuration file. If it is not given, the `burst` and `period` should both default to `1`, that is only one request can be made per second. A warning should be logged if the rate limit is not set. 

We should also include fatal logs when rateLimit has a burst/period < 1.

**Comment by rish-singhal** [comment]
Hi! I can work on this issue, could you please assign me the same. Thanks!

**Comment by prestonvasquez** [comment]
Great, it's yours!

**Comment by s4kh** [comment]
@prestonvasquez how long one should complete the task after getting assigned? I am just wondering it seems everybody asks for assignments but not doing them for a few days.

**Comment by prestonvasquez** [comment]
@rish-singhal Are you still interested in pursuing this issue?

**Comment by rish-singhal** [comment]
> @rish-singhal Are you still interested in pursuing this issue?

Yes! Will be adding a PR asap.

**Comment by prestonvasquez** [comment]
@rish-singhal Note that the organization name has changed via https://github.com/alpstable/gidari/issues/254 . You will have to re-fork the repository and migrate your changes to the new fork before making a PR. Apologies for the inconvenience.

**Comment by rish-singhal** [comment]
> @rish-singhal Note that the organization name has changed via https://github.com/alpstable/gidari/issues/254 . You will have to re-fork the repository and migrate your changes to the new fork before making a PR. Apologies for the inconvenience.

Sure no issues, thanks for informing!

**Comment by prestonvasquez** [comment]
Closed by #360
