### ISSUE TITLE
Add tests for `tools.decodeRecords`

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#205]
[`tools.decodeRecords` ](https://github.com/alpine-hodler/gidari/blob/main/tools/records.go#L227)will attempt to decode records from a `proto.UpsertRequest`. There are two types that we care about decoding: `reflect.Slice` and `reflect.Map`. We should create unit tests for both of these types.

For example:

```go
structs, _ := decodeRecords(map[string]interface{}{"x": 1})

r1, _ := structpb.NewStruct(map[string]interface{}{"int": 1})

if !reflect.DeepEqual(structs[0], r1) {
    t.Fatal("expected r1 to equal structs[0]")
}
```

(of course the actual test would need to be more robust)

**Comment by gauravgahlot** [comment]
@prestonvasquez I would to take this one. Please assign.

**Comment by prestonvasquez** [comment]
Thank you, @gauravgahlot . You are assigned :)

**Comment by gauravgahlot** [comment]
Sorry, I'm caught up with my own project for next few days. 😞

**Comment by prestonvasquez** [comment]
@gauravgahlot No worries, thank you!
