### ISSUE TITLE
Remove README.md file from internal/web/auth

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#206]

**Comment by amoghrajesh** [comment]
@prestonvasquez I would like to work on this. What exactly is the issue?

**Comment by PGautam27** [comment]
@prestonvasquez could I work on this.

**Comment by prestonvasquez** [comment]
@amoghrajesh I'm going to assign this to @PGautam27 since you're also interested in https://github.com/alpine-hodler/gidari/issues/132

For this ticket we need to either

1. Remove the README.md file from internal/web/auth 
2. Make it more clear what each of the authentication types do. If you clarify the authentication types, then this would be a Hacktoberfest ticket.

**Comment by PGautam27** [comment]
I'll remove the Readme.md file. But a small clarification, Do you want me to brief each authentication file do in a new readme fil or how do you want me to do it? cause I really want to get the hacktoberfest ticket bruh....

**Comment by prestonvasquez** [comment]
Right now this issue is an open question, so it's kind of up to you. If you want to add documentation to each of the API methods then this would qualify as complex enough for hacktoberfest. This would include going through each of [these files](https://github.com/alpine-hodler/gidari/tree/main/internal/web/auth) and

1. Adding a link to where they can read more about each method above the structs: https://github.com/alpine-hodler/gidari/blob/main/internal/web/auth/api_key.go#L33

2. Documenting more clearly each of the setter methods

**Comment by PGautam27** [comment]
works I'll do it

**Comment by prestonvasquez** [comment]
Closed by #360
