### ISSUE TITLE
Add comments to transport.Config fields

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#209]

**Comment by PGautam27** [comment]
I would like to work on it. Could you assign it to me?.

**Comment by PGautam27** [comment]
Would you mind explaining me what exactly I have to do.

**Comment by prestonvasquez** [comment]
@PGautam27 We need to unify the [`Config` struct](https://github.com/alpine-hodler/gidari/blob/main/internal/transport/transport.go#L175) fields with the README.md Usage documentation [here](https://github.com/alpine-hodler/gidari#usage). So for each of those fields add their appropriate comment from that table.

**Comment by PGautam27** [comment]
oh okok

**Comment by prestonvasquez** [comment]
This ticket is closed by #288
