### ISSUE TITLE
Make binary installable

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#216]
Need to 

1. move the `cmd/gidari.go` file to "cmd/gidari/gidari.go".
2. remove the `cmd/bash-completion.sh` script
3. remove reference to bash completion in "cmd/gidari/gidari.go"

Need to add the following to the README.md file under "Installation":

> ```
> go install github.com/alpine-hodler/gidari/cmd/gidari@latest
> ```
> 
> Gidari is not currently available as a library. Library support will be investigated in [Issue #214](https://github.com/alpine-hodler/gidari/issues/214#issue-1395594072)

**Comment by prestonvasquez** [comment]
@Himanshu664 do you want this one?

**Comment by gauravgahlot** [comment]
@prestonvasquez I would like to take it.

**Comment by Himanshu664** [comment]
@gauravgahlot I am working on it

**Comment by gauravgahlot** [comment]
Ah, alright. It's unassigned, hence the confusion.

**Comment by Himanshu664** [comment]
@prestonvasquez please review

**Comment by prestonvasquez** [comment]
@gauravgahlot Would you still like to do this?

**Comment by gauravgahlot** [comment]
Sure.

**Comment by proffapt** [comment]
the readme update part is out of the script right?

**Comment by prestonvasquez** [comment]
@proffapt Yes, sorry I've been out of town the last few days.
