### ISSUE TITLE
Deprecate NewConfig in gidari.go

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#266]
`NewConfig` is an unnecessary constructor, move the logic into the `TransportFile` routine.

**Comment by SkyWolf369** [comment]
I would like to be assigned this.

**Comment by SkyWolf369** [comment]
What exactly is needed to be done?

**Comment by prestonvasquez** [comment]
@SkyWolf369  It's yours! This issue requires two steps

1. [This routine](https://github.com/alpstable/gidari/blob/main/gidari.go#L24) will eventually be deprecated. However, right now it's [being used](https://github.com/alpstable/gidari/blob/main/cmd/gidari/cmd.go#L60) by the CLI. So we can't just delete it. 
    - Create a new issue "Delete NewConfig when Issues #265 is complete"
    - Add a comment above `NewConfig`: `// TODO #265: Remove this routine`
    
2. You copy all of the logic in `NewConfig` and put it into `TransportFile`, replacing [this line](https://github.com/alpstable/gidari/blob/main/gidari.go#L50).

**Comment by SkyWolf369** [comment]
Dont forget to reassign me to this.

**Comment by SkyWolf369** [comment]
Should be relatively easy. But cant we just do a clean switch right now and deprecate it immediately?

**Comment by prestonvasquez** [comment]
@SkyWolf369 No because the CLI depends on being able to set a log level on a config object, which it gets from NewConfig. We wont be able to remove this function until #265 is completed.

**Comment by prestonvasquez** [comment]
@SkyWolf369 This has been closed with #288
