### ISSUE TITLE
Move `proto` to `internal/proto`

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#269]
This package should not be exportable. It adds an unnecessary layer to the library that could be confusing. Use git mv to retain authorship of the underlying files:

```
git mv proto internal/proto
```

And update all of the import paths.

This will also require an update to the `Makefile` `proto` target.

**Comment by Frey0-0** [comment]
I would like to work on this issue @prestonvasquez

**Comment by prestonvasquez** [comment]
@Frey0-0 It's all you!

**Comment by prestonvasquez** [comment]
@Frey0-0 This has been closed with #288 , apologies.
