### ISSUE TITLE
Want to update README.md and also want to add CODE_OF_CONDUCT.md 

### ISSUE THREAD

**Issue by sb-decoder** [alpstable/gidari#275]
I want to add code of conduct file and also want to update main readme.md file by adding  How to contribute section and also adding contributors profiles 
can I do this please?

**Comment by prestonvasquez** [comment]
@sb-decoder We already have a CONTRIBUTING.MD file here: https://github.com/alpstable/gidari/blob/main/docs/CONTRIBUTING.md

What would go in CODE_OF_CONDUCT.md?
