### ISSUE TITLE
Add a "Ping" method to the Storage interface

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#289]
Storage needs a "Ping" method. "Ping" should indicate that a connection has been successfully establed. This ticket will require three steps:

1. Add `Ping() error` to the storage interface 
2. Add a `ping(context.Context, *testing.T)` test runner to `proto.TestRunner`
3. Implement the `Ping()` tests in `mongo.TestMongo` and `postgres.TestPostgres`

**Comment by Conor-Fleming** [comment]
I can take this up!

**Comment by Conor-Fleming** [comment]
Just want to be sure I'm clear on what is wanted here. 

-You want ```Ping()``` added to Storage interface in ```proto.storage.go```

-ping(....) test runner added to ```proto.test_runner.go``` to test new Ping() method added to storage

-It then looks like a ```pingDB []TestCase``` should be added to ```TestRunner``` struct which would be populated in ```mongo_integration_test.go``` and ```postgres_integration_test.go``` files?

-Lastly the ping method implemented in ```mongo.go``` and ```postres.go``` that should return ```ErrBadConn``` if connection is not established?

Apologies if this is obvious but just want to be sure im clear. 
Thanks in advance.

**Comment by prestonvasquez** [comment]
@Conor-Fleming That is absolutely correct. The [`closeDB` test runner](https://github.com/alpstable/gidari/blob/main/internal/proto/test_runner.go#L177) has not quite been finished yet, but the test runner for ping would look almost exactly like it.

```go
func (runner TestRunner) ping(_ context.Context, t *testing.T) {
	t.Helper()

	for _, tcase := range runner.closeDBCases {
		name := fmt.Sprintf("%s close db", tcase.Name)
		t.Run(name, func(t *testing.T) {
			t.Parallel()

                         if err := runner.Storage.Ping(); err != nil {
                             t.Errorf(...)
                         }
		})
	}
}
```

Like you suggest, you will also need to create an `AddPing` method to `TestRunner` and also include `runner.ping(ctx, t)` [here](https://github.com/alpstable/gidari/blob/main/internal/proto/test_runner.go#L95).
