### ISSUE TITLE
Add `truncate` method to `proto.TestRunner`

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#293]
The `proto.TestRunner` does not currently have a test for `storage.Truncate1. This test needs to be added and applied to the mongo.TestMongo and postgres.TestPostgres.

**Comment by RotimiFreq** [comment]
Hi @prestonvasquez,I would like to work on this issue. Do I need to be assigned to it or I can writing the tests?

**Comment by ash-kamrip** [comment]
Hi @prestonvasquez , 

I would like to assist with this one !
