### ISSUE TITLE
Finish `proto.TestRunner.closeDB` method

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#309]
This method doesn't actually test anything, it requires that "Ping" method be added to storage. when #289 is finished, we can leverage `storage.Ping` to test if the connection actually closes.

Depends on #289

**Comment by Conor-Fleming** [comment]
I can probably handle this, as its related to #337.

**Comment by Conor-Fleming** [comment]
How would you like this to be done? Its easy enough to close the DB connection in closeDB method and check the result of ping but then obviously the rest of the test cases will fail without DB connection. Would you recommend just creating a new connection after testing the close DB test case?

**Comment by prestonvasquez** [comment]
@Conor-Fleming I think the best way to handle this is to create a new connection in the closeDB runner and then just make sure that closes. It's a little tricky, consider doing something like this:

```go
type TestCase struct {
    OpenFn func() Storage
}

// closeDB will test the "Close" storage method.
func (runner TestRunner) closeDB(_ context.Context, t *testing.T) {
	t.Helper()

	for _, tcase := range runner.closeDBCases {
		name := fmt.Sprintf("%s close db", tcase.Name)
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			runner.Mutex.Lock()
			defer runner.Mutex.Unlock()

                         stg := tcase.OpenFn()
                         // Close and ping, etc
		})
	}
}
```

Then in the individual tests:

```go
		runner.AddCloseDBCases(
			[]proto.TestCase{
				{
					Name: "close postgres",
                                         OpenFn: func() Storage {
                                             stg, _ := New( ...)
                                             return stg
                                         },
				},
			}...,
		)
```

What are your thoughts on this approach?

**Comment by Conor-Fleming** [comment]
Ok, yeah that makes sense to me. Ill try that out and see where I'm at. Thanks! @prestonvasquez
