### ISSUE TITLE
Relocate `repository.NewStorage`

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#319]
The [`repository.NewStorage`](https://github.com/alpstable/gidari/blob/2b8e48875a0087fcdbb82e246c50cda81bc8f3b5/internal/repository/generic.go#L46) function more naturally belongs in the `proto` package in the `storage.go` file.

**Comment by cecobask** [comment]
@prestonvasquez, can I take on this task?

**Comment by prestonvasquez** [comment]
This change would lead to a import cycle compile error.
