### ISSUE TITLE
Update CONTRIBUTING.md "Running Integration Tests"

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#323]
The "Running Integration Tests" section needs an update to include how to run all integration tests, the include

1. `make e2e`
2. `make postgres-integration-tests`
3. `make mongo-integration-tests`

We all need to add a "Unit Tests" section that includes `make tests`

**Comment by Anuran12** [comment]
@prestonvasquez  I would like to work on this

**Comment by Anuran12** [comment]
@prestonvasquez  Can you explain which things should i add?

**Comment by prestonvasquez** [comment]
The Gidari library no longer requires integration tests. To use a storage writer, a user will need to write their own to conform to the `gidari/proto` package's writers or use an adapter library defined [here](https://github.com/alpstable/gidari#storage-adapter-library).
