### ISSUE TITLE
Add .idea to .gitignore

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#338]
ignore the goland configuration file.

**Comment by unclebinary1001** [comment]
Can I work on this?

**Comment by unclebinary1001** [comment]
Just to be clear on this requirement, I am adding the directory `.idea` to `.gitignore`, right?

**Comment by prestonvasquez** [comment]
@unclebinary1001 Just the line in the .gitignore file.

**Comment by unclebinary1001** [comment]
Okay 👍
