### ISSUE TITLE
Request RateLimiter should inherit from config RateLimiter, if it's not set

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#358]

**Comment by Conor-Fleming** [comment]
I can take this and give it a crack. @prestonvasquez.

**Comment by prestonvasquez** [comment]
@Conor-Fleming I almost have a finished version of a stronger API. Have been pretty busy the last few months but will be getting more time to focus on this. Will get it merged ASAP then will clean up the TODOs and let you know. Feel free to join the discord on the README.md if you want to DM.

**Comment by Conor-Fleming** [comment]
@prestonvasquez No worries! Sorry to bug!

**Comment by prestonvasquez** [comment]
Closed by #360
